import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Converts a JSON project structure into a downloadable ZIP file.
 * @param {Object} projectData - { project_name, files: [{ path, content }] }
 */
export const generateProjectZip = async (projectData) => {
    if (!projectData || !projectData.files) {
        console.error("Artifact Engine: Invalid project data", projectData);
        throw new Error("Cannot download: Project data is incomplete.");
    }

    const zip = new JSZip();
    // Default folder name if missing
    const folderName = projectData.project_name || 'hivemind-build';
    const root = zip.folder(folderName);

    // Process files
    projectData.files.forEach(file => {
        if (file.path) {
            // Remove leading slashes from paths (e.g. /src/App.jsx -> src/App.jsx)
            const cleanPath = file.path.startsWith('/') ? file.path.slice(1) : file.path;

            // Ensure content is a string
            const content = file.content || "";

            root.file(cleanPath, content);
        }
    });

    // Add a readme if one doesn't exist
    if (!projectData.files.find(f => f.path && f.path.toLowerCase().includes('readme.md'))) {
        root.file("README.md", `# ${folderName}\n\nGenerated by CraftMyPrompt Hivemind.\n\n## Setup\n\`npm install\`\n\`npm run dev\``);
    }

    // Generate and Trigger Download
    try {
        console.log("Compressing...");
        const content = await zip.generateAsync({ type: "blob" });
        saveAs(content, `${folderName}.zip`);
        return true;
    } catch (e) {
        console.error("Zip Generation Failed:", e);
        throw e;
    }
};
